# Generated by Django 4.2.7 on 2024-04-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_category_product_amount_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.PositiveIntegerField(default=1234567890),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='XXXX-XXX-XXXXX', max_length=64),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
